apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  KAFKA_TOPICS: "location"
  KAFKA_URL: "kafka-service.kafka.svc.cluster.local:9092"
  GRPC_URL: "udaconnect-grpc.default.svc.cluster.local:30003"
metadata:
  name: db-env
