apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-consumer
  name: udaconnect-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-consumer
  template:
    metadata:
      labels:
        service: udaconnect-consumer
    spec:
      containers:
        - image: bigsuf/udaconnect-consumer:latest
          name: udaconnect-consumer
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: KAFKA_URL
            - name: KAFKA_TOPICS
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: KAFKA_TOPICS
      restartPolicy: Always
